### ISSUE TITLE
RTH8580WF support?

### ISSUE THREAD

**Issue by vhm14u2c** [donavanbecker/homebridge-honeywell-home-thermostat#13]
**Describe Your Problem:**

Will the RTH8580WF WiFi thermostat be supported?
I believe this is the only WiFi thermostat by Honeywell that is not the t5,t6,t9

**Logs:**

```
Show the Homebridge logs here.
Remove any sensative information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here. 
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Thermostat Model:**
 RTH8580WF

# **Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Honeywell Home Plugin Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by donavanbecker** [comment]
Since I don't have one, would be hard to add support. 

If you can provide homebridge debug logs, I can potentially add support.

**Comment by vhm14u2c** [comment]
I don’t mind sending information, and debug logs.

I’m new to homebridge, but should be able to provide most if not all you ask.

Let me know where to start, and thanks.

Vince

Sent from my iPad

On Oct 31, 2020, at 7:52 AM, Donavan Becker <notifications@github.com> wrote:

﻿

Since I don't have one, would be hard to add support.

If you can provide homebridge debug logs, I can potentially add support.

**Comment by donavanbecker** [comment]
Do you have config-ui-x installed?

If so, go to the homebridge settings screen and turn on debug mode.

Once you have debug mode on, go to the logs screen and download your logs there and upload here.

**Comment by vhm14u2c** [comment]
I see setting to turn on debug mode.
How can I tell if I have config-ui-x installed?
Is there a command I can give terminal to find out?

Thanks,

Sent from my iPad

On Nov 1, 2020, at 12:38 PM, Donavan Becker <notifications@github.com> wrote:

﻿

Do you have config-ui-x installed?

If so, go to the homebridge settings screen and turn on debug mode.

Once you have debug mode on, go to the logs screen and download your logs there and upload here.

**Comment by vhm14u2c** [comment]
About the question about config-us-x, yes, is installed, (I noticed at the bottom of image I attached )
Only need to find out how to take log, and dump to text, does not allow copy/paste from browser page.
I currently don’t have Honeywell code installed.  I can reinstall though.
I had to redo an installation of homebridge when I had a bunch of kludge I mistakenly installed, so it’s cleaned up now.
[cid:5D0C04BE-47A7-4309-AAC7-A4080C1D22ED-L0-001]

Sent from my iPad

On Nov 1, 2020, at 12:38 PM, Donavan Becker <notifications@github.com> wrote:

﻿

Do you have config-ui-x installed?

If so, go to the homebridge settings screen and turn on debug mode.

Once you have debug mode on, go to the logs screen and download your logs there and upload here.

**Comment by donavanbecker** [comment]
![logs](https://user-images.githubusercontent.com/9875439/97900961-15a15700-1d01-11eb-9236-e2251da8c490.jpg)

**Comment by vhm14u2c** [comment]
I did make two sets of keys,
One for name ‘homebridge ‘
[cid:2005BF0C-D995-4620-B3C5-47C83370E8F6-L0-001]

The other for name ‘Honeywell home thermostat’
[cid:143035B6-7A98-4EB4-879E-38046CC95036-L0-001]

For both keys, it only finds my lyric camera, and don’t have option to choose the thermostat.

So far I won’t setup the lyric camera yet, and will stay focused with the thermostat.

I will send log from section you posted in a reply.
Sent from my iPad

On Nov 2, 2020, at 12:47 PM, Donavan Becker <notifications@github.com> wrote:

﻿

[logs]<https://user-images.githubusercontent.com/9875439/97900961-15a15700-1d01-11eb-9236-e2251da8c490.jpg>

**Comment by vhm14u2c** [comment]
I did choose the lyric camera(c1) since it was the only choice I had to make a token and make code appear in log.

[cid:AE87CE58-3203-40EE-942B-D9BB01B412F7-L0-001]
Sent from my iPad

On Nov 2, 2020, at 12:47 PM, Donavan Becker <notifications@github.com> wrote:

﻿

[logs]<https://user-images.githubusercontent.com/9875439/97900961-15a15700-1d01-11eb-9236-e2251da8c490.jpg>

**Comment by vhm14u2c** [comment]
Keeps updating refresh token for Honeywell home plugin
I did update router firmware last night too, which also gave homebridge a different ip via dhcp in case that has something to do with that

[cid:07602375-B7B6-4FC0-9C55-8EEDDF4C7360-L0-001]
Sent from my iPad

On Nov 2, 2020, at 11:26 PM, Vince Mayo <vince1962@live.com> wrote:

﻿ I did choose the lyric camera(c1) since it was the only choice I had to make a token and make code appear in log.

<image0.png>

Sent from my iPad

On Nov 2, 2020, at 12:47 PM, Donavan Becker <notifications@github.com> wrote:

﻿

[logs]<https://user-images.githubusercontent.com/9875439/97900961-15a15700-1d01-11eb-9236-e2251da8c490.jpg>

**Comment by donavanbecker** [comment]
If your thermostat isn't showing then I won't be able to add. Once you can get it to show and you can select when connecting your account. Then I can potentially add support.

**Comment by vhm14u2c** [comment]
I was able to find an affordable t5 thermostat.  I see it’s already HomeKit-ready.  Is there any reason to use that plugin since it’s already ‘ready’?

Thanks

Sent from my iPad

On Nov 3, 2020, at 2:45 PM, Donavan Becker <notifications@github.com> wrote:

﻿

If your thermostat isn't showing then I won't be able to add. Once you can get it to show and you can select when connecting your account. Then I can potentially add support.

**Comment by donavanbecker** [comment]
Some people use it since it connects better. But up to you.
