### ISSUE TITLE
Getting 400 error when trying to change temp

### ISSUE THREAD

**Issue by jakeflavin** [donavanbecker/homebridge-honeywell-home-thermostat#14]
Getting 400 error when trying to change temperature. Was working previously, so I assume it’s something with the Honeywell API. 

![AA7F9EC8-AA53-43EE-A061-CF48C8347F01](https://user-images.githubusercontent.com/16751450/98465056-b9bd4f00-2194-11eb-9867-1083c7ecde04.jpeg)

**Comment by donavanbecker** [comment]
Need more info. Please follow issue template.

**Comment by jakeflavin** [comment]
---
name: Bug Report
about: Create a report to help us improve
title: 'Getting 400 error when trying to change temperature.'
labels: bug
assignees: ''

---



**Describe The Bug:**
When trying to change the tempature in the morning, I’m getting a 404 error in the logs. Happens every morning. Works fine in the evening. 

**To Reproduce:**
1. Change temperature in Home app in the morning. 
2. View 404 error in logs. 
3. Temperature on thermostat does not change. 

**Expected behavior:**
I’m expecting temperature on thermostat to change. 

**Logs:**
I’m unable to pull the full log at the moment. But see the screen shot above. Will post full long in the morning. 

**Homebridge Config:**

```json

  {
            "name": "HoneywellHomeThermostat",
            "credentials": {
                "consumerKey": "",
                "consumerSecret": "",
                "refreshToken": "",
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "thermostat": {
                    "hide_fan": true,
                    "thermostatSetpointStatus": "PermanentHold"
                },
                "roompriority": {
                    "priorityType": "PickARoom"
                }
            },
            "platform": "HoneywellHomeThermostat"
        }

```


# **Environment:**

* **Node.js Version**: v12.19.0m
* **NPM Version**:  v6.14.8
* **Homebridge Version**: 1.2.3
* **Homebridge Honeywell Home Version**:
* **Homebridge Config UI X Plugin Version**: 4.32.0
* **Operating System**:  Raspbian

**Comment by donavanbecker** [comment]
@jakeflavin model of thermostat?

**Comment by jakeflavin** [comment]
It’s the Round model. 

Also. I have not had the issue over the last few days. I was consistently getting the 400 error in the log for weeks. But only in the morning. Over the last few days I enabled debug mode to get more detail about the error but I haven’t had the issue since.

**Comment by donavanbecker** [comment]
well thats good, because I have been having issues with Round Models. If you have more issues could you join the homebridge discord and reach out to me on there?
